### ISSUE TITLE
Memory leaks in SENSU when the relay socket is unstable.

### ISSUE THREAD

**Issue by chiriaev** [opower/sensu-metrics-relay#14]
Hi, . There is something I wanted to share with you. I am using the “carbon-c-relay” together with your extension. I have a cluster of six Graphite hosts load balanced with a round-robin VIP. This relay had a bug fixed since. The result was that the process was going high in CPU terms and became unresponsive. Your extension was frequently disconnecting and reconnecting back. There is a memory leak. Running that for about 24 hours made the SENSU server using about 3 GB of memory, slowly growing until the OOM killer would kick-in. That was reproducible in my environment. I didn’t test that with the “native” SENSU metrics relay, tbh. Grateful if you could have a look.

Regards, Andrei

**Comment by travis-bear** [comment]
@chiriaev "I am running this socket for 45 seconds" -- What socket are you talking about?  The receiving socket on your load balancer?

**Comment by chiriaev** [comment]
Hi, Travis-Bear. I was talking about the load balancer. I think we are fine with the relay now. Thanks for replying back.

Regards, Andrei
